before:
  hooks:
    - go mod tidy
builds:
  - id: amd
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    hooks:
      post:
        - upx -9 "{{ .Path }}"
  - id: arm
    goos:
      - linux
      - darwin
    goarch:
      - arm64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
