before:
  hooks:
    - go mod tidy
builds:
  - id: amd
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    hooks:
      post:
        - upx -9 "{{ .Path }}"
  - id: arm
    goos:
      - linux
      - darwin
    goarch:
      - arm64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - tap:
      owner: youtiaoguagua
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    homepage: "https://github.com/youtiaoguagua/ping1s"
    description: "Now you can use ping1s, you can learn an ancient poem in 1 second, isn't it interesting!"
    license: "MIT"
    skip_upload: false